import type { Metadata } from 'next';

import GlassPane from '@/components/GlassPane';
import '../global.css';

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
}

export default function DashboardLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className="h-screen w-screen rainbow-mesh p-6">
        <GlassPane className="w-full h-full flex items-center justify-center">
          {children}
        </GlassPane>
      </body>
    </html>
  );
}
